### ISSUE TITLE
Add a param for the 'events-selector.csv' config file

### ISSUE THREAD

**Issue by NRiou** [pmaugeri/ak-mpulse-annotator#2]
When we run the script with absolute path we are unable to locate the 'events-selector.csv' config file file

```
 ~ $ python3.6 /home/abc/mpulse-tools/ak-mpulse-annotator/mpulse-annotator.py -u A -c B -s C -o D -t `date -d '1 hour ago' '+%Y-%m-%dT%H:%M:%S'` -a E -m "XYZ"
Traceback (most recent call last):
  File "/home/abc/mpulse-tools/ak-mpulse-annotator/mpulse-annotator.py", line 285, in <module>
    main(sys.argv[1:])
  File "/home/abc/mpulse-tools/ak-mpulse-annotator/mpulse-annotator.py", line 251, in main
    eventsSelector = parseEventsSelector(EVENTS_SELECTOR_FILE)
  File "/home/abc/mpulse-tools/ak-mpulse-annotator/mpulse-annotator.py", line 69, in parseEventsSelector
    with open(csvfile, mode='r') as infile:
FileNotFoundError: [Errno 2] No such file or directory: 'events-selector.csv'
```

**Comment by pmaugeri** [comment]
Good point @NRiou and @ynohat. This is done in master: you can now make use of the new command line parameter '-f'.

Note that if '-f' is not specified, the tool will try by default to open events-selector.csv from the current path.
